[[constraint]]
  name = "github.com/pyr/egoscale"
  revision = "4897492dd3a23b4405af9aec45b6a9e1c1b29c73"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v2.2.0-beta"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.12.19"

[[constraint]]
  name = "github.com/rackspace/gophercloud"
  branch = "master"

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = "v0.12.0"

[prune]
  go-tests = true
  unused-packages = true
