
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "^7.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = ">=0.0.0, <1.0.0"

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = ">=0.13.0, <1.0.0"

[[constraint]]
  name = "google.golang.org/appengine"
  version = "^1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.0.0"
