
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "10.3.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "8.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/apcera/util"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.43"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  branch = "master"
  name = "github.com/pyr/egoscale"

[[constraint]]
  branch = "master"
  name = "github.com/vmware/govmomi"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"
