
[[dependencies]]
  name = "github.com/Azure/go-autorest"
  version = "^7.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/apcera/util"

[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.0.0"

[[dependencies]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[dependencies]]
  name = "github.com/go-ini/ini"
  version = "^1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/protobuf/proto"

[[dependencies]]
  branch = "master"
  name = "github.com/googleapis/gax-go"

[[dependencies]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[dependencies]]
  name = "github.com/jmespath/go-jmespath"
  version = ">=0.0.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name ="github.com/pyr/egoscale"

[[dependencies]]
  name = "github.com/vmware/govmomi"
  version = ">=0.13.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[dependencies]]
  name = "google.golang.org/appengine"
  version = "^1.0.0"

[[dependencies]]
  name = "google.golang.org/grpc"
  version = "^1.0.0"
